/**
 * Media types for the mobile app.
 * Ported from front/src/types/media.ts - types needed for share intake and inbox.
 * Used by both Android share intent and iOS share extension flows.
 */

/**
 * What a payload can put in `media_type`, which is more than the canonical enum
 * holds.
 *
 * `image_post` is an Instagram photo post or carousel, read through the text of
 * its images (task-384). It is a canonical member — the list rows carry it and
 * the detail endpoint answers it — so it gets a badge, a label and a glyph of
 * its own like every other source type.
 *
 * `document` and `audio` are the two that are not: they are what the upload
 * endpoints store on the library row (task-264), and the list endpoint returns
 * that value as-is. Being outside the canonical enum, they only ever show up in
 * a list payload — the detail endpoint normalizes them to `article` /
 * `audio_file`.
 */
export type MediaType =
  | "podcast_episode"
  | "article"
  | "youtube_video"
  | "short_video"
  | "image_post"
  | "audio_file"
  | "shared_text"
  | "document"
  | "audio"
  | "unknown";

export type SourcePlatform =
  | "spotify"
  | "apple_podcasts"
  | "deezer"
  | "rss"
  | "podcast_index"
  | "youtube"
  | "instagram"
  | "tiktok"
  | "x"
  | "whatsapp"
  | "notes"
  | "web"
  | "direct_url"
  | "unknown";

export type MediaItemStatus =
  | "ingested"
  | "resolving"
  | "processing"
  | "ready_for_artifacts"
  | "failed"
  | "cancelled";

export type ProcessingJobLifecycleStatus =
  | "pending"
  | "classifying"
  | "resolving"
  | "downloading"
  | "extracting"
  | "transcribing"
  | "ready_for_artifacts"
  | "completed"
  | "failed"
  | "cancelled";

export type ArtifactStatus = "queued" | "generating" | "ready" | "failed";

/**
 * Where the source preview stands, as `GET /api/media/{id}` reports it.
 *
 * Coarser than `ArtifactStatus` on purpose: the preview is generated by a backend
 * trigger nobody requested, so `queued` and `generating` are one and the same
 * answer to a reader — "it is coming". `failed` also covers a preview whose
 * generation was lost outright, which is why an absent `review_blurb` cannot be
 * read on its own.
 */
export type ReviewBlurbStatus = "pending" | "ready" | "failed";

/**
 * Internal artifact types as produced/accepted by the backend workers.
 * `summary` is the legacy alias still emitted by older items; new ones use
 * `summary_short` / `summary_detailed` explicitly.
 */
export type ArtifactType =
  | "summary"
  | "summary_short"
  | "summary_detailed"
  | "notes"
  | "quiz"
  | "flashcards";

/**
 * Chronological direction of a `GET /api/media` page (task-323).
 *
 * Mirrors the backend `SortDirection` literal: anything else is a 422 there, so
 * the two values are spelled out here rather than typed as a bare string.
 */
export type MediaSortDirection = "asc" | "desc";

export type TranscriptStatus =
  | "pending"
  | "extracting"
  | "transcribing"
  | "ready"
  | "failed";

export type CanonicalErrorCode =
  | "BAD_REQUEST"
  | "INVALID_URL"
  | "UNSUPPORTED_URL"
  | "SESSION_EXPIRED"
  | "NOT_AUTHORIZED"
  | "NOT_FOUND"
  | "MEDIA_NOT_FOUND"
  | "ARTIFACT_NOT_FOUND"
  | "CONFLICT"
  | "VALIDATION_ERROR"
  | "RATE_LIMITED"
  | "PAYMENT_REQUIRED"
  | "QUOTA_EXCEEDED"
  | "INSUFFICIENT_MINUTES"
  | "INTERNAL_ERROR";

/**
 * Why an ingestion job failed. Mirrors `MediaFailureCode` in
 * `media_summarizer/core/models/failure_codes.py`, and is a different vocabulary
 * from `CanonicalErrorCode`: that one names the *transport* refusal of a request
 * (a 400, a 404), this one names what happened to a media the pipeline had
 * already accepted.
 *
 * The API sends the code and nothing else about the failure — no sentence, no
 * provider text. `ERROR_CODE_MESSAGES` in `lib/getFriendlyErrorMessage.ts` owns
 * the wording, in the reader's language, and every member here must have an entry
 * there.
 */
export type MediaFailureCode =
  | "MEDIA_UNAVAILABLE"
  | "GEO_RESTRICTED"
  | "AGE_RESTRICTED"
  | "LIVE_CONTENT_UNSUPPORTED"
  | "NO_TRANSCRIBABLE_MEDIA"
  | "NO_TRANSCRIPT_AVAILABLE"
  | "POST_TEXT_EMPTY"
  | "NOT_AN_ARTICLE_PAGE"
  | "ARTICLE_TEXT_NOT_FOUND"
  | "DOCUMENT_PARSE_FAILED"
  | "PROVIDER_UNAVAILABLE"
  | "PROVIDER_RESULT_INVALID"
  | "PROVIDER_RATE_LIMITED"
  | "PROVIDER_TIMED_OUT"
  | "PROVIDER_AUTH_FAILED"
  | "PROVIDER_CREDITS_DEPLETED"
  | "PROVIDER_CONFIG_ERROR"
  | "OUT_OF_MINUTES"
  | "ITEM_TOO_LONG"
  | "INVALID_JOB_MESSAGE"
  | "SUBMISSION_FAILED"
  | "UNEXPECTED_ERROR";

export interface ProcessingProgress {
  percentage: number;
  stage: ProcessingJobLifecycleStatus;
}

export interface TranscriptInfo {
  status: TranscriptStatus;
  transcription_s3_key?: string;
  source?: string;
  language?: string;
  /**
   * Number of transcript paragraphs. Every producer reports the same unit since
   * task-232, so the value is comparable across sources.
   */
  segments_count?: number;
  duration_seconds?: number;
}

export interface ProcessingJobContract {
  job_id: string;
  status: ProcessingJobLifecycleStatus;
  progress: ProcessingProgress;
  created_at: string;
  updated_at: string;
  started_at?: string;
  completed_at?: string;
  /**
   * Present only on a failed job, and the only thing the response says about the
   * failure: the wording is built on the device (task-359).
   */
  error_code?: MediaFailureCode;
}

export interface MediaItemContract {
  media_item_id: string;
  media_key: string;
  /**
   * Display title of the durable library row — the same field `MediaListItem`
   * carries, so the detail header and the inbox vignette render one value. Null
   * while the item's metadata has not resolved yet.
   */
  title?: string | null;
  /**
   * Cover image, already resolved into a fetchable URL by the API — a re-hosted
   * cover is stored as an `s3://` locator server-side and signed on read, so a
   * client never sees one (task-304).
   */
  media_image?: string | null;
  /** Publisher of the media: a channel, a show, a site, an account. */
  creator_name?: string | null;
  original_url: string;
  normalized_url: string;
  media_type: MediaType;
  source_platform: SourcePlatform;
  status: MediaItemStatus;
  transcript: TranscriptInfo;
  /**
   * The source preview: the same triage card `MediaListItem` carries, mirrored
   * from the internal `review_blurb` artifact (task-323). Read together with
   * `review_blurb_status` — null alone says nothing about whether it is coming.
   */
  review_blurb?: ReviewBlurb | null;
  /**
   * Always sent — the API defaults it to `pending` rather than omitting it, so
   * the reader tab never has to guess how to read a null `review_blurb`.
   */
  review_blurb_status: ReviewBlurbStatus;
  folder_id?: string | null;
  created_at: string;
  updated_at: string;
}

export interface IngestUrlRequest {
  url: string;
  source_app?: string;
  locale?: string;
  idempotency_key?: string;
  folder_id?: string | null;
}

/**
 * What `POST /api/media/ingest-url` answers: the save it just created, and
 * nothing else.
 *
 * `media_item_id` is the id of *this* save — a fresh one on every submission,
 * even for content the pipeline has already processed for someone else
 * (`save_media_for_user`). That is what makes it the right target for a
 * deletion: removing it removes this save only, never another save of the same
 * content.
 */
export interface IngestUrlResponse {
  media_item_id: string;
  status: string;
  source_platform: string;
}

/**
 * Per-item detail shape. It carries no artifact projection: artifacts are an
 * append-only history per scope, so "the artifact of this type" no longer
 * exists. Read `GET /api/artifacts?scope=media&scope_id=...` through
 * `ArtifactService.listArtifacts`, which returns the history and the in-flight
 * entries in one call.
 */
export interface MediaStatusResponse {
  media_item: MediaItemContract;
  processing_job: ProcessingJobContract;
}

/**
 * The triage card mirrored from the `review_blurb` artifact (task-323).
 * Mirrors `ReviewBlurb` in `media_summarizer/core/models/user_media.py`.
 *
 * Two fields rather than one paragraph because the triage screen is scanned in
 * about three seconds, not read: `hook` is the headline, `points` the bullets. A
 * third field naming the audience shipped briefly and was dropped — it repeated
 * what the hook already said, and cost the card its last line.
 */
export interface ReviewBlurb {
  hook: string;
  points: string[];
}

/**
 * Flat list-row shape returned by `GET /api/media`.
 * Mirrors `MediaSearchItem` in `media_summarizer/api/endpoints/media.py`.
 * Distinct from `MediaStatusResponse` (which is the per-item detail shape).
 */
export interface MediaListItem {
  media_item_id: string;
  title?: string | null;
  /**
   * Triage card mirrored from the `review_blurb` artifact (task-323), for a
   * surface that has to say what a source is about without opening it.
   *
   * Nullable by contract and forever null on an item ingested before that task
   * or whose generation failed — a row without a blurb is a normal row, and the
   * only surface that reads it (the unsorted review) prints a fallback line.
   */
  review_blurb?: ReviewBlurb | null;
  /**
   * Publisher of the media — the tile's second line. Null for shared text,
   * documents and audio files, which have no creator by construction: the line
   * is then omitted rather than filled with a placeholder (task-304).
   */
  creator_name?: string | null;
  source_platform?: SourcePlatform | string | null;
  media_type?: MediaType | string | null;
  status: string;
  folder_id?: string | null;
  source_url?: string | null;
  media_image?: string | null;
  created_at: string;
  updated_at: string;
  completed_at?: string | null;
}
