"""
Canonical API/domain contracts for media ingestion and artifacts.

This module freezes the shared request/response and domain schemas used by:
- backend implementation tasks
- mobile/web client integration tasks

It is intentionally endpoint-agnostic so contracts can be reused before
runtime endpoints are fully implemented.
"""

from __future__ import annotations

from enum import Enum
from typing import Dict, Optional

from pydantic import BaseModel, Field

from media_summarizer.core.models.failure_codes import MediaFailureCode

# The blurb shape is the domain one, not a copy of it: ``MediaSearchItem`` already
# serves ``user_media.review_blurb`` verbatim on the list endpoint, and a second
# two-field model here would be free to drift from the one the mirror writes.
from media_summarizer.core.models.user_media import ReviewBlurb


class MediaType(str, Enum):
    PODCAST_EPISODE = "podcast_episode"
    ARTICLE = "article"
    YOUTUBE_VIDEO = "youtube_video"
    SHORT_VIDEO = "short_video"
    # An Instagram photo post or carousel, read through the text of its images
    # (task-384). It is not a `short_video` and not an `article`: the reader is
    # looking at a publication made of pictures, and the tile says so.
    IMAGE_POST = "image_post"
    AUDIO_FILE = "audio_file"
    SHARED_TEXT = "shared_text"
    UNKNOWN = "unknown"


class SourcePlatform(str, Enum):
    SPOTIFY = "spotify"
    APPLE_PODCASTS = "apple_podcasts"
    DEEZER = "deezer"
    RSS = "rss"
    PODCAST_INDEX = "podcast_index"
    YOUTUBE = "youtube"
    INSTAGRAM = "instagram"
    TIKTOK = "tiktok"
    X = "x"
    WHATSAPP = "whatsapp"
    # Shared note text (task-380). See `SourcePlatform.NOTES` in
    # `core/media_ingestion/domain.py` for why every unattributable text lands here.
    NOTES = "notes"
    WEB = "web"
    DIRECT_URL = "direct_url"
    UNKNOWN = "unknown"


class SharedContentType(str, Enum):
    TEXT = "text"
    AUDIO = "audio"


class MediaItemStatus(str, Enum):
    INGESTED = "ingested"
    RESOLVING = "resolving"
    PROCESSING = "processing"
    READY_FOR_ARTIFACTS = "ready_for_artifacts"
    FAILED = "failed"
    CANCELLED = "cancelled"


class TranscriptStatus(str, Enum):
    PENDING = "pending"
    EXTRACTING = "extracting"
    TRANSCRIBING = "transcribing"
    READY = "ready"
    FAILED = "failed"


class ProcessingJobLifecycleStatus(str, Enum):
    PENDING = "pending"
    CLASSIFYING = "classifying"
    RESOLVING = "resolving"
    EXTRACTING = "extracting"
    TRANSCRIBING = "transcribing"
    READY_FOR_ARTIFACTS = "ready_for_artifacts"
    COMPLETED = "completed"
    FAILED = "failed"
    CANCELLED = "cancelled"


# Transitional helper for current ProcessingJob values still present in runtime.
LEGACY_PROCESSING_JOB_STATUS_MAP: Dict[str, ProcessingJobLifecycleStatus] = {
    "pending": ProcessingJobLifecycleStatus.PENDING,
    "extracting": ProcessingJobLifecycleStatus.EXTRACTING,
    "transcribing": ProcessingJobLifecycleStatus.TRANSCRIBING,
    # Legacy name for the artifact-generation stage.
    "summarizing": ProcessingJobLifecycleStatus.READY_FOR_ARTIFACTS,
    "completed": ProcessingJobLifecycleStatus.COMPLETED,
    "failed": ProcessingJobLifecycleStatus.FAILED,
    "cancelled": ProcessingJobLifecycleStatus.CANCELLED,
}


class ArtifactType(str, Enum):
    SUMMARY_SHORT = "summary_short"
    SUMMARY_DETAILED = "summary_detailed"
    QUIZ = "quiz"
    NOTES = "notes"
    FLASHCARDS = "flashcards"


class ArtifactStatus(str, Enum):
    QUEUED = "queued"
    GENERATING = "generating"
    READY = "ready"
    FAILED = "failed"


class ReviewBlurbStatus(str, Enum):
    """Where the source preview stands, in the only three answers a client needs.

    Deliberately coarser than ``ArtifactStatus``: the preview is generated by a
    backend trigger nobody requested, so a reader has no use for the difference
    between ``queued`` and ``generating`` — both mean "it is coming, keep the
    section in place and re-read in a moment".

    ``FAILED`` also covers the case where *no* internal entry exists at all on a
    media whose processing is over. The trigger is best-effort
    (``core/services/review_blurb_service.py`` swallows every error), so a missing
    entry is not "not started yet", it is a generation that was lost —
    ``scripts/backfill_review_blurbs.py`` is what repairs it.
    """

    PENDING = "pending"
    READY = "ready"
    FAILED = "failed"


class CanonicalErrorCode(str, Enum):
    BAD_REQUEST = "BAD_REQUEST"
    INVALID_URL = "INVALID_URL"
    UNSUPPORTED_URL = "UNSUPPORTED_URL"
    SESSION_EXPIRED = "SESSION_EXPIRED"
    NOT_AUTHORIZED = "NOT_AUTHORIZED"
    NOT_FOUND = "NOT_FOUND"
    MEDIA_NOT_FOUND = "MEDIA_NOT_FOUND"
    ARTIFACT_NOT_FOUND = "ARTIFACT_NOT_FOUND"
    CONFLICT = "CONFLICT"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    RATE_LIMITED = "RATE_LIMITED"
    PAYMENT_REQUIRED = "PAYMENT_REQUIRED"
    QUOTA_EXCEEDED = "QUOTA_EXCEEDED"
    INSUFFICIENT_MINUTES = "INSUFFICIENT_MINUTES"
    INTERNAL_ERROR = "INTERNAL_ERROR"


class CanonicalErrorPayload(BaseModel):
    code: CanonicalErrorCode
    message: str
    request_id: Optional[str] = None


class CanonicalErrorResponse(BaseModel):
    error: CanonicalErrorPayload
    detail: Optional[str] = None


class ProcessingProgress(BaseModel):
    percentage: int = Field(..., ge=0, le=100)
    stage: ProcessingJobLifecycleStatus


class ProcessingJobContract(BaseModel):
    job_id: str
    status: ProcessingJobLifecycleStatus
    progress: ProcessingProgress
    created_at: str
    updated_at: str
    started_at: Optional[str] = None
    completed_at: Optional[str] = None
    # Why the job failed, as a stable identifier the client turns into a sentence
    # in the reader's own language (task-359). RFC 9457 §3.1: the `type` is the
    # contract, human-readable strings are negotiated and never authoritative --
    # so this response carries no prose about the failure at all. The diagnostic
    # context behind the code lives in `ProcessingJob.error_metadata`, which is
    # deliberately not served here: it is written for us, not for a reader.
    error_code: Optional[MediaFailureCode] = None


class TranscriptInfo(BaseModel):
    status: TranscriptStatus
    transcription_s3_key: Optional[str] = None
    source: Optional[str] = Field(
        default=None,
        description="native_transcript | deepgram | article_extractor | x_api_lookup | shared_text",
    )
    language: Optional[str] = None
    segments_count: Optional[int] = Field(
        default=None,
        ge=0,
        description=(
            "Number of transcript paragraphs. Every producer reports the same unit "
            "so the value is comparable across sources."
        ),
    )
    duration_seconds: Optional[float] = Field(default=None, ge=0)


class MediaItemContract(BaseModel):
    media_item_id: str
    media_key: str
    # Display title as stored on the durable library row -- the very value the
    # list endpoint returns, so the detail screen and the inbox show the same
    # thing instead of each inventing a label. Nullable: nothing the source
    # exposed was usable as a title.
    title: Optional[str] = None
    # Set only when ``title`` is null: the key of the label the client renders as
    # "<label> — <created_at>" in the reader's own language (task-400). Same pair
    # as the list endpoint, so the detail header and the tile read alike.
    title_label_key: Optional[str] = None
    # Cover and publisher, same two values the list endpoint returns, so the
    # detail header and the Inbox tile cannot disagree (task-304). `media_image`
    # is already resolved into a fetchable URL by the endpoint -- clients never
    # see the `s3://` locator the row stores for a re-hosted cover.
    media_image: Optional[str] = None
    creator_name: Optional[str] = None
    original_url: str
    normalized_url: str
    media_type: MediaType
    source_platform: SourcePlatform
    status: MediaItemStatus
    transcript: TranscriptInfo
    # The source preview: the hook and bullets of the internal ``review_blurb``
    # artifact, read off the mirror on the library row (task-363). Nullable, and
    # the status is what says how to read that null -- a preview being generated
    # and one that will never exist are the same absence otherwise.
    review_blurb: Optional[ReviewBlurb] = None
    review_blurb_status: ReviewBlurbStatus = ReviewBlurbStatus.PENDING
    # No artifact projection here on purpose (task-270): a scope now holds a
    # timestamped *history*, so "the artifact of this type" no longer exists.
    # The AI tab reads GET /api/artifacts?scope=media&scope_id=... which returns
    # the history and the in-flight entries in one call.
    created_at: str
    updated_at: str


class IngestUrlRequest(BaseModel):
    url: str = Field(..., min_length=1)
    source_app: Optional[str] = None
    locale: Optional[str] = None
    transcript_language: Optional[str] = Field(
        default=None,
        description=(
            "Optional override of the preferred transcript language code, e.g. 'fr'. "
            "Defaults to the authenticated user's reading_language when omitted."
        ),
    )
    idempotency_key: Optional[str] = None
    folder_id: Optional[str] = None


class IngestSharedContentRequest(BaseModel):
    share_type: SharedContentType
    source_platform: SourcePlatform
    source_app: Optional[str] = None
    locale: Optional[str] = None
    idempotency_key: Optional[str] = None
    text: Optional[str] = None
    content_mime_type: Optional[str] = None
    original_name: Optional[str] = None
    content_size_bytes: Optional[int] = Field(default=None, ge=0)


class IngestUrlResponse(BaseModel):
    media_item: MediaItemContract
    processing_job: ProcessingJobContract
    deduplicated: bool = False
    duplicate_of_media_item_id: Optional[str] = None


class MediaStatusResponse(BaseModel):
    media_item: MediaItemContract
    processing_job: ProcessingJobContract


__all__ = [
    "ArtifactStatus",
    "ArtifactType",
    "CanonicalErrorCode",
    "CanonicalErrorPayload",
    "CanonicalErrorResponse",
    "IngestSharedContentRequest",
    "IngestUrlRequest",
    "IngestUrlResponse",
    "LEGACY_PROCESSING_JOB_STATUS_MAP",
    "MediaItemContract",
    "MediaItemStatus",
    "MediaStatusResponse",
    "MediaType",
    "ProcessingJobContract",
    "ProcessingJobLifecycleStatus",
    "ProcessingProgress",
    "ReviewBlurb",
    "ReviewBlurbStatus",
    "SharedContentType",
    "SourcePlatform",
    "TranscriptInfo",
    "TranscriptStatus",
]
